name: Terraform CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Auto-format files in-place
      - name: Terraform Format (autofix)
        run: terraform fmt -recursive

      # Fail if formatting changed any tracked file
      - name: Check formatting is clean
        run: |
          git status --porcelain
          git diff --exit-code

      - name: TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.52.0
      - run: tflint --recursive

      - name: Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .

      - name: Terraform Validate
        run: terraform validate
